Main Project/Bookland/Bookland/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('', include('Books.urls')),
    path('users/', include('Users.urls')),
    path('', include('Contact.urls')),
    path('cart/', include('Cart.urls')),
    path('used-books/', include('UsedBooks.urls')),
    path('checkout/', include('Checkout.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'Books.views.error_404_view'

Main Project/Bookland/Cart/urls.py
from django.urls import path
from Cart import views

urlpatterns = [
    path('', views.cart_detail, name='cart-detail'),
    path('add-to-cart/<int:id>', views.add_to_cart, name='add-to-cart'),
    path('update-cart/<int:id>', views.update_cart, name='update-cart'),
    path('remove-from-cart/<int:id>',
         views.remove_from_cart, name='remove-from-cart')
]

Main Project/Bookland/UsedBooks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.used_books, name='used-books'),
    path('<int:pk>', views.used_books_detail, name='used-books-detail'),
    path('category/<str:slug>', views.used_categoryView,
         name='used-books-category'),
    path('s/', views.used_search, name='used-search'),
    path('listed-books/', views.listed_books, name='listed-books'),
    path('book-post/', views.book_post, name='book-post'),
    path('category-form/', views.category_form, name='category-form'),
    path('<int:pk>/update/', views.BookUpdateView.as_view(), name='update-book'),
    path('<int:pk>/delete/', views.delete_book, name='delete-book'),
]

Main Project/Bookland/UsedBooks/models.py
from django.db import models
from django.contrib.auth.models import User


class UsedCategory(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(
        default='image_not_found.png', upload_to='used_books_categories')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Categories for Used Book"


class UsedSubCategory(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(UsedCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Sub Categories for Used Book"


class UsedProduct(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    price = models.IntegerField()
    author = models.CharField(max_length=150)
    image = models.ImageField(upload_to='used_books',
                              default='image_not_found.png')
    published_date = models.DateTimeField(auto_now_add=True, null=True)
    subcategory = models.ForeignKey(UsedSubCategory, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Used Book"


class UsedComment(models.Model):
    content = models.CharField(max_length=160)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(UsedProduct, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s comment on {self.product.title}"

    class Meta:
        verbose_name = "Used Books Comment"

Main Project/Bookland/UsedBooks/forms.py
from django import forms
from .models import UsedComment, UsedProduct, UsedCategory, UsedSubCategory


class CommentForm(forms.ModelForm):
    class Meta:
        model = UsedComment
        fields = ['content', ]


class UsedProductForm(forms.ModelForm):
    image = forms.ImageField(required=True, widget=forms.TextInput(attrs={
        'accept': "image/x-png,image/gif,image/jpeg"
    })
    )

    class Meta:
        model = UsedProduct
        fields = ['title', 'author', 'price',
                  'description', 'image']

Main Project/Bookland/UsedBooks/views.py
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CommentForm, UsedProductForm
from .models import UsedCategory, UsedSubCategory, UsedProduct, UsedComment
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.template.loader import render_to_string


def used_books(request):
    products = UsedProduct.objects.order_by('-published_date')[:15]
    categories = UsedCategory.objects.all()[0:3]
    context = {
        'products': products,
        'usedcategories': categories,
    }
    return render(request, 'UsedBooks/used_books.html', context)


def used_books_detail(request, pk):
    products = get_object_or_404(UsedProduct, pk=pk)
    comments = UsedComment.objects.filter(
        product=products).order_by('-time_stamp')

    if request.method == 'POST':

        form = CommentForm(request.POST)
        if form.is_valid():
            content = request.POST.get('content')
            comment = UsedComment.objects.create(
                product=products, user=request.user, content=content)
            comment.save()
            return redirect('used-books-detail', products.id)
    else:
        form = CommentForm()
    context = {
        'products': products,
        'comments': comments,
        'form': form,
    }
    if request.is_ajax():
        html = render_to_string('UsedBooks/used_books_comments.html',
                                context, request=request)
        return JsonResponse({'form': html})
    return render(request, 'UsedBooks/used_books_detail.html', context)


def is_valid_queryparam(param):
    return param != '' and param is not None


def used_categoryView(request, slug):
    maincategorys = UsedCategory.objects.all()
    categories = UsedProduct.objects.filter(subcategory__category__name=slug)
    subcategories = UsedSubCategory.objects.filter(category__name=slug)

    name = request.GET.get('name')
    minvalue = request.GET.get('minvalue')
    maxvalue = request.GET.get('maxvalue')
    subcategory = request.GET.get('subcategory')

    paginator = Paginator(categories, 9)
    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)

    if is_valid_queryparam(name):
        categories = categories.filter(title__icontains=name)
        paginator = Paginator(categories, 9)
        page = request.GET.get('page')
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)

    if is_valid_queryparam(subcategory):
        categories = categories.filter(subcategory__name=subcategory)
        paginator = Paginator(categories, 9)
        page = request.GET.get('page')
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)

    if is_valid_queryparam(minvalue):
        categories = categories.filter(price__gte=minvalue)
        paginator = Paginator(categories, 9)
        page = request.GET.get('page')
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)

    if is_valid_queryparam(maxvalue):
        categories = categories.filter(price__lt=maxvalue)
        paginator = Paginator(categories, 9)
        page = request.GET.get('page')
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)

    context = {
        'usedcategories': categories,
        'slug': slug,
        'usedsubcategories': subcategories,
        'maincategorys': maincategorys,
        'page_obj': post_list,
        'name': name,
        'minvalue': minvalue,
        'maxvalue': maxvalue,
        'subcategory': subcategory,
    }

    return render(request, 'UsedBooks/used_books_category.html', context)


def used_search(request):
    try:
        q = request.GET.get('q')
    except:
        q = None
    if is_valid_queryparam(q):
        queries = UsedProduct.objects.filter(
            Q(title__icontains=q) | Q(description__icontains=q) | Q(author__icontains=q))
        template_name = 'UsedBooks/used_books_search.html'
        context = {
            'queries': queries,
            'q': q,
        }
    else:
        return redirect('used-books')
    return render(request, template_name, context)


@login_required
def listed_books(request):
    used_products = UsedProduct.objects.filter(
        user=request.user).order_by('-published_date')
    context = {
        'used_products': used_products,
    }
    return render(request, 'UsedBooks/listed_books.html', context)


@login_required
def category_form(request):
    categories = UsedCategory.objects.all()
    if request.method == 'POST':
        value = request.POST['cats']
        request.session['value'] = value
        return redirect('book-post')
        # print(value)
    return render(request, 'UsedBooks/category_form.html', {'categories': categories, })


# @login_required
# def book_post(request):

#     subcategories = UsedSubCategory.objects.filter(
#         category__name=request.session['value'])
#     print(subcategories)

#     form = UsedProductForm()
#     if request.method == 'POST':
#         form = UsedProductForm(request.POST)
#         if form.is_valid():
#             obj = form.save(commit=False)
#             obj.user = request.user
#             obj.save()
#             return redirect('listed-books')
#     context = {
#         'form': form,
#         'subcategories': subcategories,
#     }
#     return render(request, 'UsedBooks/uploadbook.html', context)


@login_required
def book_post(request):
    subcategories = UsedSubCategory.objects.filter(
        category__name=request.session['value'])
    if request.method == 'POST':
        title = request.POST['title']
        author = request.POST['author']
        description = request.POST['description']
        price = request.POST['price']
        image = request.FILES.get('image')
        subcategory = request.POST['subcategory']

        hello = UsedSubCategory.objects.get(id=subcategory)

        UsedProduct.objects.create(
            title=title,
            author=author,
            description=description,
            price=price,
            subcategory=hello,
            user=request.user,
            image=image
        )
        messages.success(request, 'Your book was uploaded successfully.')
        return redirect('listed-books')

    return render(request, 'UsedBooks/uploadbook.html', {'subcategories': subcategories})


class BookUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = UsedProduct
    fields = ['title', 'description', 'author',
              'image', 'price']
    template_name = 'UsedBooks/edit_uploadbook.html'
    success_url = '/used-books/listed-books'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form_valid = super().form_valid(form)
        messages.success(self.request, "Updated successfully")
        return form_valid

    def test_func(self):
        book = self.get_object()
        if self.request.user == book.user:
            return True
        return False


@login_required
def delete_book(request, pk):
    books = UsedProduct.objects.get(pk=pk)
    user = request.user
    if books.user != user:
        return HttpResponse('You are not authorized to view this page.')
    if request.method == 'POST':
        books.delete()
        messages.error(request, "Your book was deleted successfully.")
        return redirect('listed-books')
    context = {
        'books': books,
    }
    return render(request, 'UsedBooks/delete_book.html', context)

Main Project/Bookland/UsedBooks/templates/UsedBooks/category_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookland - Choose Category {% endblock %}

{% load widget_tweaks %}
{% block content %}

<div class="details">
  <h1> Upload your book </h1>
  <p>Home - Upload your book</p>
</div>
<div class="category-form-div">
  <h1>Choose your book category</h1>
  <div class="category-form">
    <form method="POST">
      {% csrf_token %}
      <select name="cats">
        {% for category in categories %}
        <option value="{{ category }}">{{ category }}</option>
        {% endfor %}
      </select>
      <button style="margin-left: 10px;">Next</button>
    </form>
  </div>

</div>

{% endblock %}

Main Project/Bookland/UsedBooks/templates/UsedBooks/delete_book.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookland - Delete Book {% endblock %}

{% block content %}

<div class="details">
  <h1>Delete Book</h1>
  <p>Used Books - Delete Book</p>
</div>

<div class="delete-book">
  <h3>Do you sure want to delete "{{ books.title }}"?</h3>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, Delete">
    <a href="{% url 'listed-books'%}">
      <button type="button">Cancel</button>
    </a>
  </form>
</div>


{% endblock %}

Main Project/Bookland/UsedBooks/templates/UsedBooks/edit_uploadbook.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookland - Edit Book {% endblock %}

{% load widget_tweaks %}
{% block content %}

<div class="details">
  <h1> Edit your book </h1>
  <p>Used Books - Edit your book</p>
</div>
<div class="outer-mainupload">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mainupload">
      {{form}}
      <button class="adbtn">Update</button>

    </div>
  </form>
</div>

{% endblock %}

Main Project/Bookland/UsedBooks/templates/UsedBooks/listed_books.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookland - Listed Books {% endblock %}

{% block content %}

<div class="details">
  <h1>My Listed Books</h1>
  <p>Used Books - My Listed Books</p>
</div>
<div class="my-wishlist">
  <div class="main1">
    {% if not used_products %}
    <div class="wishlist-empty">
      <i style=" font-size: 25px;
      margin-bottom: 10px;" class="fal fa-book-alt hey"></i>
      <p>There are no Listed books yet.</p>
      <span>Add your books and they will show here.</span>
      <a href="{% url 'category-form' %}"><button>Add your book</button></a>
    </div>
    {% else %}
    <table class="table3">
      {% for used_product in used_products %}
      <tr>
        <td class="wishlist-flex">
          <a href="{% url 'used-books-detail' used_product.id %}">
            <img src="{{ used_product.image.url }}">
          </a>
          <div class="image-desc">
            <a href="{% url 'used-books-detail' used_product.id %}">
              <h3>{{ used_product.title }}</h3>
            </a>
            <p><b>Price</b> : Rs. {{ used_product.price }}.00</p>
            <p><b>Category</b> : {{ used_product.subcategory }}</p>
          </div>
        </td>
        <td class="table-price">
          <span title="Edit"><a href="{% url 'update-book' used_product.id %}"><i class="fal fa-edit"></i></a></span>
          <span title="Delete"><a href="{% url 'delete-book' used_product.id %}"><i class="fas fa-trash"></i></a></span>
        </td>
      </tr>
      {% endfor %}
    </table>
    {% endif %}
  </div>
</div>

{% endblock %}

Main Project/Bookland/UsedBooks/templates/UsedBooks/uploadbook.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookland - Searched Results {% endblock %}

{% load widget_tweaks %}
{% block content %}

<div class="details">
  <h1> Upload your book </h1>
  <p>Home - Upload your book</p>
</div>
<div class="outer-mainupload">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mainupload">

      <label for="booktitle">Book title*</label>
      <input type="text" name="title" required>

      <label for="subcategory">Sub Category*</label>
      <select name="subcategory" id="">
        {% for cat in subcategories %}
        <option value="{{ cat.id }}">{{ cat }}</option>
        {% endfor %}
      </select>

      <label for="author">Author*</label>
      <input type="text" name="author" required>

      <label for="price">Price*</label>
      <input type="number" min='0' name="price" required>

      <label for="description">Description</label>
      <textarea required name="description" id=""></textarea>

      <label for="image">Image</label>
      <input type="file" name="image" accept="image/x-png,image/gif,image/jpeg" required>

      <button class="adbtn">Post</button>

    </div>
  </form>
</div>

{% endblock %}

Main Project/Bookland/UsedBooks/templates/UsedBooks/used_books.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookland - Used Books {% endblock %}

{% block content %}


<div class="details">
  <h1>Used Books</h1>
  <p>"You can never use a book enough"</p>
</div>


<div class="outer-used-books">

  <div class="categories">
    <p>Used Books</p>
    <h1>Categories</h1>

    <div class="inner-categories">
      {% for category in usedcategories %}
      <a href="{% url 'used-books-category' category %}">
        <div class="single-category">
          <img src="{{ category.image.url }}" alt="{{ category.name }}">
          <h3>{{ category.name|truncatechars:25 }}</h3>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>


  <div class="latest-product">
    <p class="latest-product-para">Used Books</p>
    <h1>Recetly Added</h1>
    <div class="post-book">
      <!-- <input type="text" placeholder="Search..."> -->
      <form action="{% url 'used-search' %}">
        <div class="wrapper-search">
          <input required name='q' type="text" class="input" placeholder="Search for used books..">
          <div class="searchbtn">
            <button style="background: transparent; border:none;">
              <i style="cursor: pointer;" class="fas fa-search"></i>
            </button>
          </div>


        </div>
      </form>

      <!-- <a href="uploadbook.html"><button>Post Book</button></a> -->
    </div>
    <div class="inner-latest-product">
      {% for product in products %}
      <div class="single-latest-product">
        <img src="{{ product.image.url }}" alt="">
        <div class="single-latest-product-hover"><a href="{% url 'used-books-detail' product.id %}">View Product</a>
        </div>
        <div class="product-information">
          <p>{{ product.author }}</p>
          <h3><a href="{% url 'used-books-detail' product.id %}">{{ product.title|truncatechars:25 }}</a></h3>
          <span>Rs. {{ product.price }}.00</span>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<script>

  $(document).ready(() => {
    $("#nav-id").find(".active").removeClass("active");
    $("#used-nav").addClass("active");
  })
</script>

{% endblock %}

Main Project/Bookland/UsedBooks/templates/UsedBooks/used_books_category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookland - Used Category ({{slug}}) {% endblock %}

{% block content %}

{% if not maincategorys %}

<div class="details">
  <h1>Page not found</h1>
  <a style="text-decoration: none;" href="{% url 'home' %}">
    <span><i class="fal fa-arrow-left"></i> &nbsp; BACK TO HOMEPAGE</span>
  </a>
</div>

{% else %}

<div class="details">
  <h1>{{ slug }}</h1>
  <p>Used Books - Category</p>
</div>


<section>
  <div class="container">
    <div class="row">
      <div class="side">

        <div class="sidebar">
          <div class="head">Browse Categories</div>
          <div class="cate-content">
            <ul>
              {% for maincategory in maincategorys %}
              <li class="cate-list"><a href=" {% url 'used-books-category' maincategory %}">
                  {{maincategory}}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>


        <div style="margin-top: 20px;" class="sidebar">
          <div class="head">Browse Categories</div>
          <div class="cate-content">
            <form method='GET'>
              <ul>
                {% for subcat in usedsubcategories  %}
                <li class="cate-list">
                  <input id="{{ subcat }}" value="{{ subcat }}" class="radiobtn" type="radio" name="subcategory"
                    {% if subcat.name == subcategory %} checked {% endif %}>
                  <label for="{{ subcat }}">{{ subcat }}
                    ({{subcat.usedproduct_set.count}})</label>
                </li>
                {% endfor %}
              </ul>

          </div>
        </div>
        <div class="price-filter">
          <div class="rangeslider">
            <!-- <input name="minvalue" type="range" min="100" max="3000" value="100" id="myrange"
                            class="slider">
                        <p>Price : $<span id="value"></span></p> -->

            <span class="labelprice" for="">Min Price :</span><br>
            <input type="number" name="minvalue" id="" value="{{ minvalue }}"><br>
            <span class="labelprice" for="">Max Price :</span><br>
            <input type="number" name="maxvalue" value="{{ maxvalue }}">

          </div>


          <button class="filterbtn">Filter</button>
        </div>
        </form>
      </div>


      <div class="product">
        <form method="GET">
          <div class="searchbar">
            <div class="srch">


              <input name='name' type="text" placeholder="Search" {% if name != None %} value="{{ name }}" {% endif %}>
              <div class="srchbtn">
                <button>
                  <i class="fa fa-search" aria-hidden="true"></i>
                </button>

              </div>

            </div>
          </div>
        </form>
        <div class="product-area">
          {% if not page_obj %}

          <div style="height: 400px;" class="no-books-found-div">
            <h1 style="text-align: center;">No books found</h1>
          </div>
          {% else %}
          <div class="Area">
            {% for cat in page_obj %}
            <div class="product-detail">

              <div class="card ">
                <div class="single-latest-product-hover">
                  <a href="{% url 'used-books-detail' cat.id %}">View Product</a></div>
                <div class="card_img">
                  <img class="card-img" src="{{ cat.image.url }}" alt="">

                </div>
                <div class="card-body">
                  <p>{{ cat.author }}</p>
                  <a style="text-decoration: none;" href="{% url 'used-books-detail' cat.id %}">
                    <h4 class="card-product__title">{{ cat.title|truncatechars:25 }}</h4>
                  </a>
                  <p class="card-product__price">Rs. {{ cat.price }}.00</p>
                </div>
              </div>

            </div>
            {% endfor %}
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="pagination-div">

      {% if page_obj %}
      {% if page_obj.has_previous %}
      <a class="" href="?page={{ page_obj.previous_page_number }}"><button>Previous</button></a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
      <a class="" href="?page={{ num }}"><button>{{ num }}</button></a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
      <a class="" href="?page={{ num }}"><button>{{ num }}</button></a>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <a class="" href="?page={{ page_obj.next_page_number }}"><button>Next</button></a>
      {% endif %}
      {% endif %}
    </div>



  </div>
</section>
{% endif %}


{% endblock %}

Main Project/Bookland/UsedBooks/templates/UsedBooks/used_books_comments.html
{% load humanize %}
{% load widget_tweaks %}

{% if user.is_authenticated %}
<form method="POST" class='usedcomment-form-ajax'>
  {% csrf_token %}
  {% render_field form.content class="" placeholder="Write a comment.." autocomplete="off" %}
  <button>Comment</button>
</form>
{% else %}
<form method="POST" class='usedcomment-form-ajax'>
  {% csrf_token %}
  {% render_field form.content class="" placeholder="Please login to write a comment" autocomplete="off" %}
  <button disabled>Comment</button>
</form>
{% endif %}

<div class="commented-section">
  {% if comments %}
  {% for comment in comments %}

  <div class="single-commented-section">
    <div class="question">
      <div class="question-person">
        <img src="{{ comment.user.profile.image.url }}" alt="{{ comment.user.username }}">
        <span>{{ comment.content }}</span>
      </div>
      <span class="commentor">{{ comment.user.first_name }} {{ comment.user.last_name }} -
        {{ comment.time_stamp|naturaltime }}</span>
      <div class="answer">
      </div>
    </div>
  </div>
  {% endfor %}

  {% else %}
  <h1 style="margin-top: 10px;">No comments available. Be the first one to comment.</h1>
  {% endif %}
</div>

Main Project/Bookland/UsedBooks/templates/UsedBooks/used_books_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookland - {{products.title}} {% endblock %}

{% load humanize %}
{% load widget_tweaks %}
{% block content %}

<div class="details">
  <h1>Product Details</h1>
  <p>Used Books - Details</p>
</div>

<div class="product-detail-page">
  <div class="picture-details">
    <div class="picture-details-img"> <img src="{{ products.image.url }}" alt="{{ products.title }}"></div>
    <div class="details-info">
      <p>By {{ products.author }}</p>
      <h1>{{ products.title }}</h1>
      <p class="price">Rs. {{ products.price }}.00 </p>
      <p>Category : {{ products.subcategory.name }}</p>

      <div class="seller-details">
        <div class="seller-details-header">
          <h3>Seller Details</h3>
        </div>
        <div class="seller-details-body">
          <p><b>Sold By</b> : {{ products.user.first_name }} {{ products.user.last_name }}</p>
          <p><b>Email</b> : {{ products.user.email }}</p>
          <p><b>Address</b> : {{ products.user.profile.address }}</p>
          <p><b>Phone</b> : {{ products.user.phone }}</p>
        </div>
      </div>
    </div>
  </div>
  <div class="product-description">
    <div class="product-description-header">
      <h1>Description</h1>
    </div>
    <div class="describe">
      <p>{{ products.description }}</p>
    </div>
  </div>
  <div class="product-comments">
    <div class="product-comments-header">
      <h1>Comments</h1>
    </div>
    <div class="comment" id='used-comment'>

      {% include 'UsedBooks/used_books_comments.html' %}


    </div>
  </div>
</div>


<script>
  $(document).ready(function (event) {
    $(document).on('submit', '.usedcomment-form-ajax', function (event) {
      event.preventDefault();
      $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        dataType: 'json',
        success: function (response) {
          $('#used-comment').html(response['form'])
        },
        error: function (rs, e) {
          console.log(rs.responseText);
        }
      })
    })
  })
</script>

{% endblock %}

Main Project/Bookland/UsedBooks/templates/UsedBooks/used_books_search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookland - Searched Results {% endblock %}

{% block content %}

<div class="details">
  <h1>Searched results for: {{ q|truncatechars:15 }}</h1>
</div>



<div class="main-search-div">
  <form action="{% url 'used-search' %}">
    <div class="wrapper-search">

      <input required name='q' value='{{ q }}' type="text" class="input" placeholder="Search for used books..">

      <div class="searchbtn">
        <button style="background: transparent; border:none;">
          <i style="cursor: pointer;" class="fas fa-search"></i>
        </button>
      </div>


    </div>
  </form>

  {% if not queries %}
  <h1 style="text-align: center;margin-top: -10px;">Not Found</h1>
  {% else %}
  <h1 style="text-align: center;margin-top: -10px;"> ({{queries.count}}) book{{ queries|pluralize }} found</h1>
  {% endif %}


  <div class="latest-product">
    <div class="inner-latest-product">

      {% for query in queries %}
      <div class="single-latest-product">
        <img src="{{ query.image.url }}" alt="">
        <div class="single-latest-product-hover"><a href="{% url 'product-detail' query.id %}">View Product</a></div>
        <div class="product-information">
          <p>{{ query.author }}</p>
          <h3><a href="{% url 'product-detail' query.id %}">{{ query.title|truncatechars:25 }}</a></h3>
          <span>Rs. {{ query.price }}.00</span>
        </div>
      </div>
      {% endfor %}


    </div>
  </div>
</div>


{% endblock %}